echo "============================================="
echo "======= MOBILECENTER POSTCLONE SCRIPT ======="
echo "============================================="

echo "MOBILECENTER_BUILD_ID $MOBILECENTER_BUILD_ID"
echo "MOBILECENTER_BRANCH $MOBILECENTER_BRANCH"
echo "MOBILECENTER_SOURCE_DIRECTORY $MOBILECENTER_SOURCE_DIRECTORY"
echo "MOBILECENTER_OUTPUT_DIRECTORY $MOBILECENTER_OUTPUT_DIRECTORY"
echo "MOBILECENTER_TRIGGER $MOBILECENTER_TRIGGER"

echo "MOBILECENTER_UWP_SOLUTION $MOBILECENTER_UWP_SOLUTION"
echo "MOBILECENTER_UWP_CONFIGURATION $MOBILECENTER_UWP_CONFIGURATION"
