echo "============================================="
echo "======= MOBILECENTER POSTBUILD SCRIPT ======="
echo "============================================="

Write-Host "MOBILECENTER_BUILD_ID $MOBILECENTER_BUILD_ID"
Write-Host "MOBILECENTER_BRANCH $MOBILECENTER_BRANCH"
Write-Host "MOBILECENTER_SOURCE_DIRECTORY $MOBILECENTER_SOURCE_DIRECTORY"
Write-Host "MOBILECENTER_OUTPUT_DIRECTORY $MOBILECENTER_OUTPUT_DIRECTORY"
Write-Host "MOBILECENTER_TRIGGER $MOBILECENTER_TRIGGER"

Write-Host "MOBILECENTER_UWP_SOLUTION $MOBILECENTER_UWP_SOLUTION"
Write-Host "MOBILECENTER_UWP_CONFIGURATION $MOBILECENTER_UWP_CONFIGURATION"
